//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diyetisyenlik.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food2
    {
        public int FoodId { get; set; }
        public string FoodName { get; set; }
        public int DietId { get; set; }
        public string Proportion { get; set; }
        public string Meal { get; set; }
    
        public virtual Diet Diet { get; set; }
    }
}
