//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diyetisyenlik.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yazilimmimarisiEntities : DbContext
    {
        public yazilimmimarisiEntities()
            : base("name=yazilimmimarisiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diet> Diet { get; set; }
        public virtual DbSet<Disease> Disease { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<Food2> Food2 { get; set; }
        public virtual DbSet<Proportion> Proportion { get; set; }
        public virtual DbSet<Sick> Sick { get; set; }
        public virtual DbSet<SickDiet> SickDiet { get; set; }
        public virtual DbSet<SickDisease> SickDisease { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
