//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diyetisyenlik.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proportion
    {
        public int ProportionId { get; set; }
        public int DietId { get; set; }
        public int FoodId { get; set; }
        public string Proportion1 { get; set; }
        public string Meal { get; set; }
    
        public virtual Diet Diet { get; set; }
        public virtual Food Food { get; set; }
    }
}
