//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diyetisyenlik.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SickDisease
    {
        public int SickDiseaseId { get; set; }
        public int SickId { get; set; }
        public int DiseaseId { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual Sick Sick { get; set; }
    }
}
